/enemy_state_node:
  ros__parameters:
    armors_topic: "/detector/armors"
    enemy_pose_topic: "/enemy_pose"
    enemy_state_topic: "/enemy_state"
    enemy_velocity_topic: "/enemy_velocity"
    frame_id: "map"
    window_size: 5
    smoothing_alpha: 0.6
    min_velocity_threshold: 0.02


