keypoints:
  - id: 1 #台阶下
    x: 4.54225
    y: -1.53015
    
    
  - id: 2 #打符处
    x: 6.74087
    y: 2.66909
    
    
  - id: 3 #飞坡下
    x: 3.89596
    y: 5.62592
    
    
  - id: 4 #自家高地边缘
    x: 4.51808
    y: 2.63143
    
  
  - id: 5 #保卫英雄掉射点
    x: 1.11277
    y: 5.27047
    
  
  - id: 6 #上坡底（鼠洞口）
    x: 5.78455
    y: -5.58767
    
 
  - id: 7 #基底前
    x: 0.867278
    y: -1.50694


  - id: 8 #基地右
    x: -0.105693
    y: -4.04582
    
   
  - id: 9 #堡垒右
    x: 2.96661
    y: -3.88679
    
    
  - id: 10 #盲道前拐角
    x: 1.06372
    y: -7.1813
    
    
  - id: 11 #盲道前
    x: 1.10293
    y: -8.23538
    
    
  - id: 12 #盲道后
    x: 5.5391
    y: -8.20107
    
    
  - id: 13 #前哨点
    x: 8.37223
    y: 4.03626
    
   
  - id: 14 #我方前哨增益点
    x: 8.69894
    y: -5.51467
    
    
  - id: 15 #符右下角
    x: 9.06651
    y: -3.13161
    
   
  - id: 16 #符左下角
    x: 9.30728
    y: -0.550471
    
    
  - id: 17 #我方高地增益点
    x: 8.8372
    y: 2.08652
    
    
  - id: 18 #符左上角
    x: 12.6578
    y: 1.14879
    
    
  - id: 19 #对面上台阶处（符正前方）
    x: 13.7905
    y: -1.2312
    
    
  - id: 20 #符右上角
    x: 12.6215
    y: -4.63655
    
    
  - id: 21 #对面前前哨站增益点右边点
    x: 13.8187
    y: 1.84407
    
    
  - id: 22 #对面前哨站增益点左边点
    x: 13.9397
    y: 3.12803
    
    
  - id: 23 #对面飞坡右点
    x: 14.5942
    y: 4.88468
    
    
  - id: 24 #对面过盲道后拦截点
    x: 15.4624
    y: 5.2463
    
    
  - id: 25 #对面上盲道坡的拐点
    x: 21.2318
    y: 3.74888
    
    
  - id: 26 #对面上坡前的点
    x: 17.0193
    y: 2.24763
    
   
  - id: 27 #对面堡垒左边
    x: 20.0112
    y: 0.395513
    
    
  - id: 28 #对面上台阶前
    x: 17.8471
    y: -1.3839
    
    
  - id: 29 #对面堡垒右边
    x: 19.1392
    y: -3.52064
    
    
  - id: 30 #对面打符点
    x: 15.0525
    y: -5.6808
    
